"""Reusable column type aliases.

Declared once so that every table spells the same concept the same way. The
alternative — repeating ``mapped_column(BigInteger, Identity(always=True),
primary_key=True)`` on eleven tables — is how one table quietly ends up with
``GENERATED BY DEFAULT`` and an importable primary key.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from typing import Annotated

from sqlalchemy import BigInteger, Identity, Numeric, SmallInteger, func, text
from sqlalchemy.orm import mapped_column

__all__ = [
    "BigIntPK",
    "CreatedAt",
    "DeletedAt",
    "PublicUUID",
    "Score",
    "SmallCount",
    "SmallInt",
    "UpdatedAt",
]

# ``GENERATED ALWAYS`` rather than ``BY DEFAULT``: the application has no
# business supplying a surrogate key, and ``ALWAYS`` makes that a database
# error instead of a convention.
BigIntPK = Annotated[
    int,
    mapped_column(BigInteger, Identity(always=True), primary_key=True),
]

# Generated database-side so a row inserted by a migration or a manual repair
# still gets a valid external identifier (06 §2).
PublicUUID = Annotated[
    uuid.UUID,
    mapped_column(server_default=func.gen_random_uuid(), unique=True, nullable=False),
]

CreatedAt = Annotated[
    dt.datetime,
    mapped_column(server_default=func.now(), nullable=False),
]

# ``onupdate`` is application-side: the sole writer is this application, and a
# trigger would be a second moving part maintaining a column nobody reads for
# correctness. Revisit if out-of-band writes ever become legitimate.
UpdatedAt = Annotated[
    dt.datetime,
    mapped_column(server_default=func.now(), onupdate=func.now(), nullable=False),
]

DeletedAt = Annotated[dt.datetime | None, mapped_column(nullable=True, default=None)]

SmallInt = Annotated[int, mapped_column(SmallInteger)]

# Non-negative counters: default 0 and never null, so rollup arithmetic never
# has to handle a NULL that means zero.
SmallCount = Annotated[
    int,
    mapped_column(SmallInteger, nullable=False, server_default=text("0")),
]

# 1.00–5.00 self-reported and averaged values. NUMERIC, not FLOAT: these are
# compared and constrained, and binary floating point makes ``<= 5`` a lie.
Score = Annotated[Decimal | None, mapped_column(Numeric(3, 2), nullable=True)]
