"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Created: ${create_date}

Checklist before merging (06_Database_Schema.md §19):
  [ ] Autogenerated output read line by line — partial indexes, functional
      indexes and generated columns are NOT produced by autogenerate.
  [ ] `downgrade()` implemented and actually tested, not just written.
  [ ] `alembic upgrade head` then `alembic downgrade base` runs clean.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
