r"""identity and tracking tables

Revision ID: 8e3f7c8e2582
Revises:
Created: 2026-07-29 14:21:49.095932

Checklist before merging (06_Database_Schema.md §19):
  [x] Autogenerated output read line by line against docs/06_Database_Schema.md
      §2-9 and cross-checked with \d in psql — partial indexes, the
      lower(name) functional index, and the duration_seconds generated
      column all came out correct without hand-editing.
  [x] `downgrade()` implemented and actually tested, not just written.
  [x] `alembic upgrade head` then `alembic downgrade base` runs clean.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8e3f7c8e2582"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "public_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("timezone", sa.Text(), server_default=sa.text("'UTC'"), nullable=False),
        sa.Column("locale", sa.Text(), server_default=sa.text("'en'"), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("onboarding_completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deleted')", name=op.f("ck_users_status")
        ),
        sa.CheckConstraint(
            "display_name IS NULL OR length(display_name) BETWEEN 1 AND 64",
            name=op.f("ck_users_display_name_length"),
        ),
        sa.CheckConstraint("length(trim(timezone)) > 0", name=op.f("ck_users_timezone_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("public_id", name=op.f("uq_users_public_id")),
    )
    op.create_index(
        "ix_users_deleted_at",
        "users",
        ["deleted_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NOT NULL"),
    )
    op.create_table(
        "exercise_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("activity_type", sa.Text(), server_default=sa.text("'other'"), nullable=False),
        sa.Column("duration_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("intensity", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_type IN ('cardio', 'strength', 'walking', 'sport', 'other')",
            name=op.f("ck_exercise_logs_activity_type"),
        ),
        sa.CheckConstraint(
            "intensity IS NULL OR intensity IN ('low', 'moderate', 'high')",
            name=op.f("ck_exercise_logs_intensity"),
        ),
        sa.CheckConstraint(
            "duration_minutes BETWEEN 1 AND 600", name=op.f("ck_exercise_logs_duration_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exercise_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_logs")),
    )
    op.create_index("ix_exercise_logs_local_date", "exercise_logs", ["local_date"], unique=False)
    op.create_index(
        "ix_exercise_logs_user_occurred",
        "exercise_logs",
        ["user_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "mood_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("mood", sa.SmallInteger(), nullable=False),
        sa.Column("energy", sa.SmallInteger(), nullable=True),
        sa.Column("stress", sa.SmallInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "energy IS NULL OR energy BETWEEN 1 AND 5", name=op.f("ck_mood_logs_energy_range")
        ),
        sa.CheckConstraint("mood BETWEEN 1 AND 5", name=op.f("ck_mood_logs_mood_range")),
        sa.CheckConstraint(
            "note IS NULL OR length(note) <= 1000", name=op.f("ck_mood_logs_note_length")
        ),
        sa.CheckConstraint(
            "stress IS NULL OR stress BETWEEN 1 AND 5", name=op.f("ck_mood_logs_stress_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_mood_logs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mood_logs")),
    )
    op.create_index("ix_mood_logs_local_date", "mood_logs", ["local_date"], unique=False)
    op.create_index(
        "ix_mood_logs_user_recorded",
        "mood_logs",
        ["user_id", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_table(
        "privacy_settings",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "profile_visibility", sa.Text(), server_default=sa.text("'private'"), nullable=False
        ),
        sa.Column(
            "stats_visibility", sa.Text(), server_default=sa.text("'private'"), nullable=False
        ),
        sa.Column(
            "leaderboard_opt_in", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "research_consent", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("research_consent_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "profile_visibility IN ('private', 'friends', 'groups')",
            name=op.f("ck_privacy_settings_profile_visibility"),
        ),
        sa.CheckConstraint(
            "stats_visibility IN ('private', 'friends', 'groups')",
            name=op.f("ck_privacy_settings_stats_visibility"),
        ),
        sa.CheckConstraint(
            "(research_consent = false) OR (research_consent_at IS NOT NULL)",
            name=op.f("ck_privacy_settings_research_consent_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_privacy_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_privacy_settings")),
    )
    op.create_table(
        "sleep_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("duration_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("bedtime_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("wake_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("quality", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bedtime_at IS NULL OR wake_at IS NULL OR wake_at > bedtime_at",
            name=op.f("ck_sleep_logs_wake_after_bedtime"),
        ),
        sa.CheckConstraint(
            "duration_minutes BETWEEN 0 AND 1440", name=op.f("ck_sleep_logs_duration_range")
        ),
        sa.CheckConstraint(
            "quality IS NULL OR quality BETWEEN 1 AND 5", name=op.f("ck_sleep_logs_quality_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sleep_logs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sleep_logs")),
    )
    op.create_index("ix_sleep_logs_local_date", "sleep_logs", ["local_date"], unique=False)
    op.create_index("uq_sleep_logs_user_date", "sleep_logs", ["user_id", "local_date"], unique=True)
    op.create_table(
        "subjects",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("colour", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "colour IS NULL OR colour ~ '^#[0-9A-Fa-f]{6}$'", name=op.f("ck_subjects_colour_format")
        ),
        sa.CheckConstraint(
            "length(trim(name)) BETWEEN 1 AND 100", name=op.f("ck_subjects_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subjects_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
    )
    op.create_index(
        "ix_subjects_user_active",
        "subjects",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("NOT is_archived"),
    )
    op.create_index(
        "uq_subjects_user_name",
        "subjects",
        ["user_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "telegram_accounts",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_username", sa.Text(), nullable=True),
        sa.Column("language_code", sa.Text(), nullable=True),
        sa.Column(
            "linked_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "telegram_id > 0", name=op.f("ck_telegram_accounts_telegram_id_positive")
        ),
        sa.CheckConstraint(
            "telegram_username IS NULL OR length(telegram_username) <= 32",
            name=op.f("ck_telegram_accounts_username_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_telegram_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_telegram_accounts")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_telegram_accounts_telegram_id")),
    )
    op.create_table(
        "study_sessions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subject_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'in_progress'"), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column(
            "duration_seconds",
            sa.Integer(),
            sa.Computed(
                "CASE WHEN ended_at IS NULL THEN NULL ELSE EXTRACT(EPOCH FROM (ended_at - started_at))::INTEGER END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("planned_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("focus_score", sa.SmallInteger(), nullable=True),
        sa.Column("session_type", sa.Text(), server_default=sa.text("'focus'"), nullable=False),
        sa.Column(
            "interruption_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'in_progress') = (ended_at IS NULL)",
            name=op.f("ck_study_sessions_status_end_consistency"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at <= started_at + INTERVAL '12 hours'",
            name=op.f("ck_study_sessions_max_duration"),
        ),
        sa.CheckConstraint(
            "session_type IN ('focus', 'review', 'practice', 'reading', 'other')",
            name=op.f("ck_study_sessions_session_type"),
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'abandoned', 'discarded')",
            name=op.f("ck_study_sessions_status"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at",
            name=op.f("ck_study_sessions_end_after_start"),
        ),
        sa.CheckConstraint(
            "focus_score IS NULL OR focus_score BETWEEN 1 AND 5",
            name=op.f("ck_study_sessions_focus_range"),
        ),
        sa.CheckConstraint(
            "interruption_count >= 0", name=op.f("ck_study_sessions_interruptions_non_negative")
        ),
        sa.CheckConstraint(
            "planned_minutes IS NULL OR planned_minutes > 0",
            name=op.f("ck_study_sessions_planned_minutes_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_study_sessions_subject_id_subjects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_study_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_sessions")),
    )
    op.create_index(
        "ix_study_sessions_rollup",
        "study_sessions",
        ["local_date", "user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_study_sessions_user_started",
        "study_sessions",
        ["user_id", sa.literal_column("started_at DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_study_sessions_user_subject",
        "study_sessions",
        ["user_id", "subject_id", "local_date"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_study_sessions_one_active",
        "study_sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_study_sessions_one_active",
        table_name="study_sessions",
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.drop_index(
        "ix_study_sessions_user_subject",
        table_name="study_sessions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_study_sessions_user_started",
        table_name="study_sessions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_study_sessions_rollup",
        table_name="study_sessions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("study_sessions")
    op.drop_table("telegram_accounts")
    op.drop_index("uq_subjects_user_name", table_name="subjects")
    op.drop_index(
        "ix_subjects_user_active",
        table_name="subjects",
        postgresql_where=sa.text("NOT is_archived"),
    )
    op.drop_table("subjects")
    op.drop_index("uq_sleep_logs_user_date", table_name="sleep_logs")
    op.drop_index("ix_sleep_logs_local_date", table_name="sleep_logs")
    op.drop_table("sleep_logs")
    op.drop_table("privacy_settings")
    op.drop_index("ix_mood_logs_user_recorded", table_name="mood_logs")
    op.drop_index("ix_mood_logs_local_date", table_name="mood_logs")
    op.drop_table("mood_logs")
    op.drop_index("ix_exercise_logs_user_occurred", table_name="exercise_logs")
    op.drop_index("ix_exercise_logs_local_date", table_name="exercise_logs")
    op.drop_table("exercise_logs")
    op.drop_index(
        "ix_users_deleted_at",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NOT NULL"),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
